# Generated by Django 3.1.4 on 2021-02-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('job', models.CharField(max_length=30, verbose_name='Trabajo')),
                ('image', models.ImageField(default='null', upload_to='empleados', verbose_name='Identificacion')),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Editado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
